server {
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    listen 80;
    listen [::]:80;
    server_name   blog.wflixu.cn;

    location / {
        root /home/ubuntu/code/nblog/dist;
        index index.html index.htm index.nginx-debian.html;
        try_files $uri $uri/ $uri/index.html =404;

        # non existent pages
        error_page 404 /404.html;

        # a folder without index.html raises 403 in this setup
        error_page 403 /404.html;

        # adjust caching headers
        # files in the assets folder have hashes filenames
        location ~* ^/assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}

 # blog
server {
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    listen       443 ssl;
    server_name   blog.wflixu.cn;
    ssl_certificate      /home/ubuntu/docs/blog.wflixu.cn_bundle.crt;
    ssl_certificate_key  /home/ubuntu/docs/blog.wflixu.cn.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    client_max_body_size 10m;

    location / {
        root /home/ubuntu/code/nblog/dist;
        index index.html index.htm index.nginx-debian.html;
        try_files $uri $uri/ $uri/index.html =404;

        # non existent pages
        error_page 404 /404.html;

        # a folder without index.html raises 403 in this setup
        error_page 403 /404.html;

        # adjust caching headers
        # files in the assets folder have hashes filenames
        location ~* ^/assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}