import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <div className="logo">
            <Image
              src="/imgs/logo.png"
              width={24}
              height={24}
              alt="Picture of the author"
            />
            <span>
              Today blog
            </span>
          </div>
          <div className="nav">
            <a href="/">
              Home
            </a>
            <a href="/about">
              About
            </a>
          </div>

        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
